# Generated by Django 3.1.1 on 2020-09-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0003_auto_20200923_2034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
