# Generated by Django 3.1.1 on 2020-09-25 11:55

from django.db import migrations, models
import galleria.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0004_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=galleria.models.get_upload_path),
        ),
    ]
