# Generated by Django 3.1.1 on 2020-10-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0005_auto_20200925_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='subfolder',
            field=models.CharField(default='', max_length=20),
        ),
    ]
