# Generated by Django 3.1.1 on 2020-10-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0006_image_subfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(default=123, editable=False, upload_to='thumbs'),
            preserve_default=False,
        ),
    ]
