# Generated by Django 3.1.1 on 2020-10-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0007_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='subfolder',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
