# Generated by Django 3.1.1 on 2020-10-03 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0008_auto_20201002_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='/', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='subfolder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleria.folder'),
        ),
    ]
