# Generated by Django 3.1.1 on 2020-10-09 07:26

from django.db import migrations, models
import galleria.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0010_auto_20201003_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='full_hd',
            field=models.ImageField(null=True, upload_to=galleria.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='subfolder',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
