# Generated by Django 3.1.1 on 2020-10-15 20:54

from django.db import migrations, models
import galleria.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0011_auto_20201009_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(editable=False, upload_to=galleria.models.get_upload_path),
        ),
    ]
