# Generated by Django 3.1.1 on 2020-10-16 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0012_auto_20201015_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
