# Generated by Django 3.1.1 on 2020-10-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0013_image_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aspect_ratio',
            field=models.FloatField(default=1.77),
        ),
    ]
