# Generated by Django 3.1.1 on 2020-10-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0014_image_aspect_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='aspect_ratio',
            field=models.FloatField(),
        ),
    ]
